version: "3"

services:
  #nginx
  node:
    build:
      context: docker/nodejs
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      #- NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8082:8080"
    tty: true
  #nginx
  nginx_front:
    build:
      context: docker/nginx
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/
